project:
  type: website
  render:
    - "*.qmd"
    - "!LICENSE.md"

website:
  title: nutriverse
  site-url: https://nutriverse.io
  description: Developing an integrated collection of R packages designed to support and facilitate various nutrition data analytics.
  navbar:
    title: nutriverse
    #background: success
    logo: images/nutriverse_neg.png
    logo-alt: nutriverse
    tools:
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@nutriverse
        rel: me
      - icon: bluesky
        aria-label: Bluesky
        href: https://bsky.app/profile/nutriverse.io
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/company/nutriverse-community
      - icon: github
        aria-label: GitHub
        href: https://github.com/nutriverse
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Packages
        href: packages/index.qmd
      - text: Community
        menu:
          - text: Community
            href: community/index.qmd
          - text: Code of Conduct
            href: code-of-conduct.qmd
      - text: About
        menu:
          - href: about/team.qmd
          - href: about/contact.qmd
  open-graph:
    site-name: nutriverse
  page-footer:
    center: "Copyright 2024-2026, Oxford iHealth"
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/nutriverse/nutriverse.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/nutriverse/nutriverse.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-Z9SDQC2LZH"
    anonymize-ip: true

format:
  html:
    theme: [pulse, custom.scss]
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: false